Avoid error with missing prettier types
Previously I was seeing the following error when running `npm run build`:

    error TS2688: Cannot find type definition file for 'prettier'.

    The file is in the program because:
    Entry point for implicit type library 'prettier'